version: "3"
services:

  nginx:
    ports: [ "3000:80" ]

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=prod
    environment:
      - NODE_ENV=prod
      - MONGO_PORT=27017
      - MONGO_USERNAME=abracadabra
      - MONGO_PASSWORD=allakhazam
      - MONGO_IP=mongo
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=secret
    command: node index.js
