version: "3"
services:

  nginx:
    ports: [ "3000:80" ]

  node-app:
    build:
      context: .
      args:
        - NODE_ENV=dev
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=dev
      - MONGO_PORT=27017
      - MONGO_USERNAME=abracadabra
      - MONGO_PASSWORD=allakhazam
      - MONGO_IP=mongo
      - REDIS_URL=redis
      - REDIS_PORT=6379
      - SESSION_SECRET=secret
    command: npm run dev

  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=abracadabra
      - MONGO_INITDB_ROOT_PASSWORD=allakhazam
